# Generated by Django 4.2.16 on 2025-05-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('interest_rate', models.FloatField()),
                ('term_months', models.IntegerField()),
            ],
        ),
    ]
