# Generated by Django 4.2.16 on 2025-05-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=8, verbose_name='공시종료일'),
        ),
        migrations.AddField(
            model_name='product',
            name='dcls_month',
            field=models.CharField(default=1, max_length=6, verbose_name='공시제출월'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='dcls_strt_day',
            field=models.CharField(blank=True, max_length=8, verbose_name='공시시작일'),
        ),
        migrations.AddField(
            model_name='product',
            name='etc_note',
            field=models.TextField(blank=True, verbose_name='기타안내'),
        ),
        migrations.AddField(
            model_name='product',
            name='fin_co_no',
            field=models.CharField(default=1, max_length=20, verbose_name='금융회사코드'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='intr_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='기준이율(%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='join_deny',
            field=models.CharField(blank=True, max_length=1, verbose_name='가입제한(Y/N)'),
        ),
        migrations.AddField(
            model_name='product',
            name='join_way',
            field=models.CharField(blank=True, max_length=100, verbose_name='가입방법'),
        ),
        migrations.AddField(
            model_name='product',
            name='save_trm',
            field=models.IntegerField(blank=True, null=True, verbose_name='예치기간(개월)'),
        ),
        migrations.AddField(
            model_name='product',
            name='spcl_cnd',
            field=models.TextField(blank=True, verbose_name='우대조건'),
        ),
        migrations.AddField(
            model_name='product',
            name='supr_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='우대이율(%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='금융회사명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='상품명'),
        ),
    ]
