# Generated by Django 4.2.16 on 2025-05-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_dcls_end_day_product_dcls_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='term_months',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='상품코드'),
        ),
    ]
