# Generated by Django 4.2.16 on 2025-05-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='intr_rate',
            field=models.FloatField(default=0, verbose_name='기준이율(%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=64, verbose_name='상품코드'),
        ),
        migrations.AlterField(
            model_name='product',
            name='save_trm',
            field=models.IntegerField(default=0, verbose_name='예치기간(개월)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supr_rate',
            field=models.FloatField(default=0, verbose_name='우대이율(%)'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_id', 'save_trm')},
        ),
    ]
