# Generated by Django 4.2.16 on 2025-05-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_intr_rate_alter_product_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dcls_month',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dcls_strt_day',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='etc_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fin_co_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='intr_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='join_deny',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='join_way',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='save_trm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='spcl_cnd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supr_rate',
            field=models.FloatField(default=0),
        ),
    ]
