# Generated by Django 4.2.16 on 2025-05-26 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0005_alter_product_bank_name_alter_product_dcls_end_day_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_prdt_cd", models.TextField(unique=True)),
                ("kor_co_nm", models.TextField()),
                ("fin_prdt_nm", models.TextField()),
                ("etc_note", models.TextField()),
                ("join_deny", models.IntegerField()),
                ("join_member", models.TextField()),
                ("join_way", models.TextField()),
                ("spcl_cnd", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SavingProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_prdt_cd", models.TextField(unique=True)),
                ("kor_co_nm", models.TextField()),
                ("fin_prdt_nm", models.TextField()),
                ("etc_note", models.TextField()),
                ("join_deny", models.IntegerField()),
                ("join_member", models.TextField()),
                ("join_way", models.TextField()),
                ("spcl_cnd", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SavingOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_prdt_cd", models.TextField()),
                ("intr_rate_type_nm", models.CharField(max_length=100)),
                ("intr_rate", models.FloatField()),
                ("intr_rate2", models.FloatField()),
                ("save_trm", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.savingproducts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepositOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_prdt_cd", models.TextField()),
                ("intr_rate_type_nm", models.CharField(max_length=100)),
                ("intr_rate", models.FloatField()),
                ("intr_rate2", models.FloatField()),
                ("save_trm", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.depositproducts",
                    ),
                ),
            ],
        ),
    ]
