# Generated by Django 4.2.16 on 2025-05-26 02:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_age_user_bio_user_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_number',
            field=models.CharField(default=accounts.models.generate_membership_number, editable=False, max_length=20, unique=True),
        ),
    ]
