# Generated by Django 4.2.16 on 2025-05-27 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_depositproducts_savingproducts_savingoptions_and_more"),
        ("accounts", "0004_user_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscribed",
        ),
        migrations.AddField(
            model_name="user",
            name="subscirbed_saving_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribers",
                to="products.savingproducts",
                verbose_name="가입한 적금 상품",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscribed_deposit_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribers",
                to="products.depositproducts",
                verbose_name="가입한 정기예금 상품",
            ),
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term_months", models.IntegerField()),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.depositproducts",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
