# Generated by Django 4.2.16 on 2025-05-27 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_depositproducts_savingproducts_savingoptions_and_more'),
        ('accounts', '0006_remove_user_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_deposit_products',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='products.depositproducts'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_saving_products',
            field=models.ManyToManyField(blank=True, related_name='subscribers_saving', to='products.savingproducts'),
        ),
    ]
