# Generated by Django 4.2.21 on 2025-05-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommodityPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity", models.CharField(max_length=10)),
                ("date", models.DateField()),
                ("price", models.IntegerField()),
            ],
            options={
                "unique_together": {("commodity", "date")},
            },
        ),
    ]
