# Generated by Django 4.2.21 on 2025-05-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_commodityprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodityprice",
            name="price",
            field=models.FloatField(),
        ),
    ]
