# Generated by Django 4.2.21 on 2025-05-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_commodityprice_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodityprice",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
